layout_spectrum: 0
typography_spectrum: 0.6451613
color:
  saturation: 0.5
  lightness: 0.7043011
  brandStrength: 0.3655914
  rhythmicContrast: 0.2806466
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
name: Nex9
